#version 460

#extension GL_EXT_shader_explicit_arithmetic_types_int64 : require
#extension GL_EXT_shader_explicit_arithmetic_types_int16 : require

layout(push_constant) uniform Params{
    uint16_t value;    // 用 16-bit int 存 bfloat16
    int64_t numel;
} params;

layout(std430, binding = 0) buffer Output{
    uint16_t data[];
};

void main(){
    uint idx = gl_GlobalInvocationID.x;
    if (idx >= params.numel) return;
    data[idx] = params.value;
}
