#version 450
#extension GL_EXT_shader_explicit_arithmetic_types_int64 : require

layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

layout(push_constant) uniform Params {
    int value;
    int64_t numel;
} params;

layout(std430, binding = 0) buffer Output {
    int data[];
};

void main() {
    uint idx = gl_GlobalInvocationID.x;
    if (int64_t(idx) >= params.numel) return;
    data[idx] = params.value;
}

