#version 460

#extension GL_EXT_shader_explicit_arithmetic_types : require
#extension GL_EXT_shader_8bit_storage : require
#extension GL_EXT_shader_explicit_arithmetic_types_int64 : require


layout(push_constant) uniform Params{
  int8_t value;
  int64_t numel;
}params;

layout(std430, binding = 0) buffer Output{
  int8_t data[];
};

void main(){
  uint idx = gl_GlobalInvocationID.x;
  if(idx >= params.numel) return;
  data[idx] = params.value;
}

