#version 460
#extension GL_EXT_shader_explicit_arithmetic_types_int64 : require
#extension GL_EXT_shader_explicit_arithmetic_types : require
#extension GL_EXT_shader_8bit_storage : require

layout(push_constant) uniform Params {
    int64_t numel;
} params;

layout(std430, binding = 0) buffer Data {
    int8_t values[];
};

void main() {
    uint idx = gl_GlobalInvocationID.x;
    if (int64_t(idx) >= params.numel) return;
    values[idx] = max(values[idx], int8_t(0));
}
